More cross-compiling fixes

diff --git a/recipe/patches/0003-avoid-f2cFortran-test-in-configure.patch b/recipe/patches/0003-avoid-f2cFortran-test-in-configure.patch
--- a/recipe/patches/0003-avoid-f2cFortran-test-in-configure.patch
+++ b/recipe/patches/0003-avoid-f2cFortran-test-in-configure.patch
@@ -1,6 +1,6 @@
 diff -ruN -x __pycache__ -x obj -x '*~' -x tags -x TAGS hdfeos5.orig/configure hdfeos5/configure
 --- hdfeos5.orig/configure	2010-08-30 17:47:03.000000000 +0200
-+++ hdfeos5/configure	2022-11-23 14:25:24.194589939 +0100
++++ hdfeos5/configure	2022-11-23 17:31:50.213393428 +0100
 @@ -20355,6 +20355,7 @@
  
  { echo "$as_me:$LINENO: checking for fc2Fortran macro" >&5
@@ -15,5 +15,90 @@ diff -ruN -x __pycache__ -x obj -x '*~' -x tags -x TAGS hdfeos5.orig/configure h
  echo $ECHO_N "checking for H5Fcreate in -lhdf5... $ECHO_C" >&6; }
 +ac_cv_lib_hdf5_H5Fcreate=yes
  if test "${ac_cv_lib_hdf5_H5Fcreate+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+@@ -22577,67 +22579,7 @@
+ # Check whether HDF5 threadsafety is enabled
+ { echo "$as_me:$LINENO: checking if HDF5 threadsafe mode is enabled" >&5
+ echo $ECHO_N "checking if HDF5 threadsafe mode is enabled... $ECHO_C" >&6; }
+-if test "$cross_compiling" = yes; then
+-  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+-See \`config.log' for more details." >&5
+-echo "$as_me: error: cannot run test program while cross compiling
+-See \`config.log' for more details." >&2;}
+-   { (exit 1); exit 1; }; }
+-else
+-  cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-
+-#include "hdf5.h"
+-
+-int main(void) {
+-#ifdef H5_HAVE_THREADSAFE
+-  return 0;
+-#else
+-  return 1;
+-#endif
+-}
+-_ACEOF
+-rm -f conftest$ac_exeext
+-if { (ac_try="$ac_link"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_link") 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+-  { (case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_try") 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; }; then
+-   { echo "$as_me:$LINENO: result: yes" >&5
+-echo "${ECHO_T}yes" >&6; }
+-    THREADSAFE="yes"
+-else
+-  echo "$as_me: program exited with status $ac_status" >&5
+-echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-( exit $ac_status )
+-{ echo "$as_me:$LINENO: result: no" >&5
+-echo "${ECHO_T}no" >&6; }
+-    THREADSAFE="no"
+-fi
+-rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+-fi
+-
+-
++THREADSAFE="yes"
+ 
+ # Record threadsafe status in config.h and for Makefiles
+ if test "X$THREADSAFE" = "Xyes"; then
+@@ -22664,6 +22606,7 @@
+ 
+   { echo "$as_me:$LINENO: checking for hdf5 szip decoding filter" >&5
+ echo $ECHO_N "checking for hdf5 szip decoding filter... $ECHO_C" >&6; }
++  he5_cv_hdf5_szip_can_decode=yes
+   if test "${he5_cv_hdf5_szip_can_decode+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+@@ -22753,6 +22696,7 @@
+ 
+   { echo "$as_me:$LINENO: checking for hdf5 szip encoding filter" >&5
+ echo $ECHO_N "checking for hdf5 szip encoding filter... $ECHO_C" >&6; }
++  he5_cv_hdf5_szip_can_encode=yes
+   if test "${he5_cv_hdf5_szip_can_encode+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
